### ISSUE TITLE
Polymode was rewriten

### ISSUE THREAD

**Issue by vspinu** [smaret/gildas-mode#8]
Just letting you know that polymode has been simplified and "fixed" in many ways. The current version of glidas-mode won't' work with new polymode due to changes in architecture. See https://polymode.github.io/ for the new documentation.  

In case you are still interested in maintaining this mode, I can help with the transition.

**Comment by smaret** [comment]
Thanks for the heads-up. Yes, your help with the transition would be much appreciated.

**Comment by vspinu** [comment]
Would be good to see an example of a script with chunks.

**Comment by smaret** [comment]
Here is a trivial example:
https://gist.github.com/smaret/d7cdcf69851581610939b53aa0fa280e
